# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ac42d411f48269ebca4024946dab2ceefdfdca0fde63ce9fec382e3da818e900716ea9767d90ee26dcf0e65b517018bd48e841ed8056577a01be42335e47b06

test:
  secret_key_base: 937577bcbbc32b2e5cdf945cf4ad1e170677a09f7250d512d3c34158ac20e78a46da98958d52855cd15abd6d5f9302fbfeaef584e4b6c0782bcb1fa00d1850b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
